[build]
  command = "npm install && npm run build"
  publish = "dist"          
  functions = "netlify/functions"

# Set a longer timeout for all functions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]
  [functions."*"]
    timeout = 40

# Redirect all frontend routes to index.html (important for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
