[build]
  command = "npm install && npm run build"
  publish = "dist"          
  functions = "netlify/functions"

# Set a longer timeout for all functions
[functions]
  timeout = 25 # Increase timeout to 25 seconds
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

# Redirect all frontend routes to index.html (important for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
